### ISSUE TITLE
BUG:空调制冷温度可以低到零下40度

### ISSUE THREAD

**Issue by Core2002** [jwjjgs/kt.jwjjgs.cn#1]
BUG:空调制冷温度可以低到零下40度

**Comment by jwjjgs** [comment]
> BUG:空调制冷温度可以低到零下40度
代码已经更正 制热(16~+∞) 制冷(-273~30) 制冷只要不低于绝对零度，都给安排上 /斜眼笑

**Comment by jwjjgs** [comment]
合理合理
